"""Regenerate display images with Python + Pillow; retain originals for zoom."""
from pathlib import Path
from PIL import Image, ImageOps

root = Path(__file__).resolve().parents[1]
assets = root / 'src/assets'
output = assets / 'optimized'
output.mkdir(exist_ok=True)
imports = []
entries = []
original_bytes = display_bytes = 0
for index, source in enumerate(sorted((assets / 'works').glob('*'))):
    if source.suffix.lower() not in ('.jpg', '.png'):
        continue
    original = ImageOps.exif_transpose(Image.open(source)).convert('RGB')
    variants = []
    for width in sorted({min(size, original.width) for size in (480, 960, 1600)}):
        resized = original.resize((width, round(original.height * width / original.width)), Image.Resampling.LANCZOS)
        target = output / f'{source.stem}-{width}.webp'
        resized.save(target, 'WEBP', quality=82, method=6)
        name = f'image{index}w{width}'
        imports.append(f"import {name} from '../assets/optimized/{target.name}'")
        variants.append((name, width))
        display_bytes += target.stat().st_size
    imports.append(f"import original{index} from '../assets/works/{source.name}'")
    srcset = ', '.join('${' + name + '} ' + str(width) + 'w' for name, width in variants)
    entries.append(f'  [original{index}]: {{ src: {variants[-1][0]}, srcSet: `{srcset}` }},')
    original_bytes += source.stat().st_size

portrait = ImageOps.exif_transpose(Image.open(assets / 'portrait.jpg')).convert('RGB')
portrait.thumbnail((336, 420), Image.Resampling.LANCZOS)
portrait.save(output / 'portrait.webp', 'WEBP', quality=85, method=6)
(root / 'src/data/imageVariants.ts').write_text(
    '// Generated by scripts/optimize-images.py\n' + '\n'.join(imports) +
    '\n\nexport const imageVariants: Record<string, { src: string; srcSet: string }> = {\n' +
    '\n'.join(entries) + '\n}\n', encoding='utf-8')
print(f'Works: originals {original_bytes:,} bytes; all display variants {display_bytes:,} bytes')
print(f'Portrait: {(assets / "portrait.jpg").stat().st_size:,} -> {(output / "portrait.webp").stat().st_size:,} bytes')
