// Generated by scripts/optimize-images.py
import image0w480 from '../assets/optimized/abcd-01-480.webp'
import image0w960 from '../assets/optimized/abcd-01-960.webp'
import image0w1440 from '../assets/optimized/abcd-01-1440.webp'
import original0 from '../assets/works/abcd-01.png'
import image1w480 from '../assets/optimized/abcd-02-480.webp'
import image1w960 from '../assets/optimized/abcd-02-960.webp'
import image1w1440 from '../assets/optimized/abcd-02-1440.webp'
import original1 from '../assets/works/abcd-02.png'
import image2w480 from '../assets/optimized/abcd-03-480.webp'
import image2w960 from '../assets/optimized/abcd-03-960.webp'
import image2w1440 from '../assets/optimized/abcd-03-1440.webp'
import original2 from '../assets/works/abcd-03.png'
import image3w480 from '../assets/optimized/abcd-04-480.webp'
import image3w960 from '../assets/optimized/abcd-04-960.webp'
import image3w1440 from '../assets/optimized/abcd-04-1440.webp'
import original3 from '../assets/works/abcd-04.png'
import image4w480 from '../assets/optimized/explorer-01-480.webp'
import image4w900 from '../assets/optimized/explorer-01-900.webp'
import original4 from '../assets/works/explorer-01.jpg'
import image5w480 from '../assets/optimized/explorer-02-480.webp'
import image5w900 from '../assets/optimized/explorer-02-900.webp'
import original5 from '../assets/works/explorer-02.jpg'
import image6w480 from '../assets/optimized/explorer-03-480.webp'
import image6w900 from '../assets/optimized/explorer-03-900.webp'
import original6 from '../assets/works/explorer-03.jpg'
import image7w480 from '../assets/optimized/muzexr-01-480.webp'
import image7w960 from '../assets/optimized/muzexr-01-960.webp'
import image7w1600 from '../assets/optimized/muzexr-01-1600.webp'
import original7 from '../assets/works/muzexr-01.png'
import image8w480 from '../assets/optimized/muzexr-02-480.webp'
import image8w960 from '../assets/optimized/muzexr-02-960.webp'
import image8w1600 from '../assets/optimized/muzexr-02-1600.webp'
import original8 from '../assets/works/muzexr-02.png'
import image9w480 from '../assets/optimized/sophon-01-480.webp'
import image9w900 from '../assets/optimized/sophon-01-900.webp'
import original9 from '../assets/works/sophon-01.jpg'
import image10w480 from '../assets/optimized/sophon-02-480.webp'
import image10w900 from '../assets/optimized/sophon-02-900.webp'
import original10 from '../assets/works/sophon-02.jpg'
import image11w480 from '../assets/optimized/sophon-03-480.webp'
import image11w900 from '../assets/optimized/sophon-03-900.webp'
import original11 from '../assets/works/sophon-03.jpg'
import image12w340 from '../assets/optimized/sphere-lab-01-340.webp'
import original12 from '../assets/works/sphere-lab-01.jpg'
import image13w310 from '../assets/optimized/sphere-lab-02-310.webp'
import original13 from '../assets/works/sphere-lab-02.jpg'
import image14w310 from '../assets/optimized/sphere-lab-03-310.webp'
import original14 from '../assets/works/sphere-lab-03.jpg'
import image15w480 from '../assets/optimized/sphere-lab-color-480.webp'
import image15w960 from '../assets/optimized/sphere-lab-color-960.webp'
import image15w1600 from '../assets/optimized/sphere-lab-color-1600.webp'
import original15 from '../assets/works/sphere-lab-color.jpg'
import image16w480 from '../assets/optimized/sphere-lab-poster-480.webp'
import image16w845 from '../assets/optimized/sphere-lab-poster-845.webp'
import original16 from '../assets/works/sphere-lab-poster.png'
import image17w480 from '../assets/optimized/vr-cpr-01-480.webp'
import image17w960 from '../assets/optimized/vr-cpr-01-960.webp'
import image17w1600 from '../assets/optimized/vr-cpr-01-1600.webp'
import original17 from '../assets/works/vr-cpr-01.png'
import image18w480 from '../assets/optimized/vr-cpr-02-480.webp'
import image18w960 from '../assets/optimized/vr-cpr-02-960.webp'
import image18w1600 from '../assets/optimized/vr-cpr-02-1600.webp'
import original18 from '../assets/works/vr-cpr-02.png'
import image19w480 from '../assets/optimized/vr-cpr-03-480.webp'
import image19w960 from '../assets/optimized/vr-cpr-03-960.webp'
import image19w1600 from '../assets/optimized/vr-cpr-03-1600.webp'
import original19 from '../assets/works/vr-cpr-03.png'
import image20w480 from '../assets/optimized/vr-fire-extinguisher-01-480.webp'
import image20w960 from '../assets/optimized/vr-fire-extinguisher-01-960.webp'
import image20w1600 from '../assets/optimized/vr-fire-extinguisher-01-1600.webp'
import original20 from '../assets/works/vr-fire-extinguisher-01.png'
import image21w480 from '../assets/optimized/vr-fire-extinguisher-02-480.webp'
import image21w960 from '../assets/optimized/vr-fire-extinguisher-02-960.webp'
import image21w1600 from '../assets/optimized/vr-fire-extinguisher-02-1600.webp'
import original21 from '../assets/works/vr-fire-extinguisher-02.png'
import image22w480 from '../assets/optimized/vr-fire-extinguisher-03-480.webp'
import image22w960 from '../assets/optimized/vr-fire-extinguisher-03-960.webp'
import image22w1600 from '../assets/optimized/vr-fire-extinguisher-03-1600.webp'
import original22 from '../assets/works/vr-fire-extinguisher-03.png'
import image23w480 from '../assets/optimized/vr-mall-01-480.webp'
import image23w900 from '../assets/optimized/vr-mall-01-900.webp'
import original23 from '../assets/works/vr-mall-01.jpg'
import image24w480 from '../assets/optimized/vr-mall-02-480.webp'
import image24w900 from '../assets/optimized/vr-mall-02-900.webp'
import original24 from '../assets/works/vr-mall-02.jpg'
import image25w480 from '../assets/optimized/vr-mall-03-480.webp'
import image25w900 from '../assets/optimized/vr-mall-03-900.webp'
import original25 from '../assets/works/vr-mall-03.jpg'

export const imageVariants: Record<string, { src: string; srcSet: string }> = {
  [original0]: { src: image0w1440, srcSet: `${image0w480} 480w, ${image0w960} 960w, ${image0w1440} 1440w` },
  [original1]: { src: image1w1440, srcSet: `${image1w480} 480w, ${image1w960} 960w, ${image1w1440} 1440w` },
  [original2]: { src: image2w1440, srcSet: `${image2w480} 480w, ${image2w960} 960w, ${image2w1440} 1440w` },
  [original3]: { src: image3w1440, srcSet: `${image3w480} 480w, ${image3w960} 960w, ${image3w1440} 1440w` },
  [original4]: { src: image4w900, srcSet: `${image4w480} 480w, ${image4w900} 900w` },
  [original5]: { src: image5w900, srcSet: `${image5w480} 480w, ${image5w900} 900w` },
  [original6]: { src: image6w900, srcSet: `${image6w480} 480w, ${image6w900} 900w` },
  [original7]: { src: image7w1600, srcSet: `${image7w480} 480w, ${image7w960} 960w, ${image7w1600} 1600w` },
  [original8]: { src: image8w1600, srcSet: `${image8w480} 480w, ${image8w960} 960w, ${image8w1600} 1600w` },
  [original9]: { src: image9w900, srcSet: `${image9w480} 480w, ${image9w900} 900w` },
  [original10]: { src: image10w900, srcSet: `${image10w480} 480w, ${image10w900} 900w` },
  [original11]: { src: image11w900, srcSet: `${image11w480} 480w, ${image11w900} 900w` },
  [original12]: { src: image12w340, srcSet: `${image12w340} 340w` },
  [original13]: { src: image13w310, srcSet: `${image13w310} 310w` },
  [original14]: { src: image14w310, srcSet: `${image14w310} 310w` },
  [original15]: { src: image15w1600, srcSet: `${image15w480} 480w, ${image15w960} 960w, ${image15w1600} 1600w` },
  [original16]: { src: image16w845, srcSet: `${image16w480} 480w, ${image16w845} 845w` },
  [original17]: { src: image17w1600, srcSet: `${image17w480} 480w, ${image17w960} 960w, ${image17w1600} 1600w` },
  [original18]: { src: image18w1600, srcSet: `${image18w480} 480w, ${image18w960} 960w, ${image18w1600} 1600w` },
  [original19]: { src: image19w1600, srcSet: `${image19w480} 480w, ${image19w960} 960w, ${image19w1600} 1600w` },
  [original20]: { src: image20w1600, srcSet: `${image20w480} 480w, ${image20w960} 960w, ${image20w1600} 1600w` },
  [original21]: { src: image21w1600, srcSet: `${image21w480} 480w, ${image21w960} 960w, ${image21w1600} 1600w` },
  [original22]: { src: image22w1600, srcSet: `${image22w480} 480w, ${image22w960} 960w, ${image22w1600} 1600w` },
  [original23]: { src: image23w900, srcSet: `${image23w480} 480w, ${image23w900} 900w` },
  [original24]: { src: image24w900, srcSet: `${image24w480} 480w, ${image24w900} 900w` },
  [original25]: { src: image25w900, srcSet: `${image25w480} 480w, ${image25w900} 900w` },
}
